# Generated by Django 2.0 on 2017-12-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('share_ids', models.CharField(max_length=300)),
                ('host_ids', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
