# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostRide',
            fields=[
                ('host_ride_id', models.AutoField(primary_key=True, serialize=False)),
                ('host_ride_from', models.CharField(max_length=50)),
                ('host_ride_to', models.CharField(max_length=50)),
                ('host_ride_date', models.DateField()),
                ('host_ride_time', models.TimeField()),
                ('host_ride_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('host_ride_note', models.TextField()),
            ],
            options={
                'db_table': 'host_ride',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShareRide',
            fields=[
                ('share_ride_id', models.AutoField(primary_key=True, serialize=False)),
                ('share_ride_from', models.CharField(max_length=50)),
                ('share_ride_to', models.CharField(max_length=50)),
                ('share_ride_date', models.DateField()),
                ('share_ride_time', models.TimeField()),
                ('share_ride_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('share_ride_note', models.TextField()),
            ],
            options={
                'db_table': 'share_ride',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('share_ids', models.CharField(max_length=300)),
                ('host_ids', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
