# Generated by Django 2.0 on 2017-12-20 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dibe', '0002_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
