# Generated by Django 2.0 on 2017-12-22 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dibe', '0003_auto_20171220_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
