# Generated by Django 2.0 on 2017-12-23 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dibe', '0004_auto_20171223_0352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostride',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shareride',
            options={},
        ),
    ]
