# Generated by Django 2.0 on 2017-12-25 04:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dibe', '0005_auto_20171223_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostride',
            name='host_ride_user_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shareride',
            name='share_ride_user_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hostride',
            name='host_ride_note',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='shareride',
            name='share_ride_note',
            field=models.TextField(default=''),
        ),
    ]
