# Generated by Django 2.0 on 2018-04-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dibe', '0005_auto_20180322_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=300),
        ),
    ]
