# Generated by Django 2.0 on 2017-12-25 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dibe', '0006_auto_20171225_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareride',
            name='share_ride_date',
        ),
        migrations.RemoveField(
            model_name='shareride',
            name='share_ride_time',
        ),
    ]
