# Generated by Django 2.0 on 2017-12-25 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dibe', '0007_auto_20171225_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareride',
            name='share_ride_note',
        ),
    ]
