# Generated by Django 2.0 on 2017-12-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dibe', '0008_remove_shareride_share_ride_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='host_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='share_count',
            field=models.IntegerField(default=0),
        ),
    ]
