# Generated by Django 2.0 on 2017-12-26 05:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dibe', '0009_auto_20171226_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareride',
            name='share_ride_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shareride',
            name='share_ride_note',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='shareride',
            name='share_ride_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
