# Generated by Django 2.0 on 2017-12-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dibe', '0010_auto_20171226_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostride',
            name='host_ride_date',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='hostride',
            name='host_ride_time',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='shareride',
            name='share_ride_date',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='shareride',
            name='share_ride_time',
            field=models.CharField(max_length=300),
        ),
    ]
