# Generated by Django 2.0 on 2018-01-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dibe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostride',
            name='host_ride_price',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='shareride',
            name='share_ride_price',
            field=models.CharField(max_length=300),
        ),
    ]
